<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <StaticWebAssetBasePath>App_Plugins/$(AssemblyName)</StaticWebAssetBasePath>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>Limbo.Umbraco.Tables.Assets</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="wwwroot\Legacy\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Umbraco.Cms.Core"/>
        <PackageReference Include="Umbraco.Cms.Web.Website"/>
        <PackageReference Include="Skybrud.Essentials"/>
    </ItemGroup>

</Project>
