<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
 
    <Company>Limbo</Company>
    <Product>Limbo Tables</Product>
    <Authors>Anders Bjerner</Authors>
    <Copyright>Copyright © $([System.DateTime]::UtcNow.ToString(`yyyy`))</Copyright>
    <Title>Limbo Tables</Title>
    <PackageId>Limbo.Umbraco.Tables</PackageId>
    <Description>Table editor for Umbraco.</Description>
  </PropertyGroup>

  <!-- Include NuGet dependencies -->
  <ItemGroup>
    <PackageReference Include="Skybrud.Essentials" />
    <PackageReference Include="Umbraco.Cms.Core" />
    <PackageReference Include="Umbraco.Cms.Web.Website" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Limbo.Umbraco.Tables.StaticAssets\Limbo.Umbraco.Tables.StaticAssets.csproj" />
  </ItemGroup>

  <!-- Generate XML documentation -->
  <PropertyGroup>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>

</Project>
